### ISSUE TITLE
Is there a way to jsonate relation like one to one relations?

### ISSUE THREAD

**Issue by ialex** [Rootbuzz/JSONate#4]
i would like to have a three like json returned when im searching for objects with relations using selected_related and/or prefetch_related

**Comment by ialex** [comment]
It was posible using to_json:

def to_json(self):
        return {
            'text': self.text,
            'user': self.user.username,
            'parent': None if self.parent is None else self.parent.id,
            'votes': self.votes.count(),
            'created': self.created,
            'id': self.id
        }

**Comment by jiaaro** [comment]
@ialex cool. alternatively, if the field is on this model you can save yourself a database query like: `'parent': self.parent_id,` or include the parent to be serialized as well: `'parent': self.parent,`
